### ISSUE TITLE
Properly handle import-only files that forward other files

### ISSUE THREAD

**Issue by jathak** [sass/migrator#129]
Right now, a case like:
```scss
// entrypoint.scss
@import "direct";

a {
  b: $direct;
  c: $indirect;
}

// _direct.scss
@use "indirect";

$direct: indirect.$indirect + 1;

// _direct.import.scss
@forward "direct";
@forward "indirect";
```

is incorrectly migrated to

```
// entrypoint.scss
@use "direct";

a {
  b: direct.$direct;
  c: direct.$indirect;
}
```

because the migrator doesn't properly account for the `@forward "indirect"` going away when migrating from `@import` to `@use`.

Fixing this is necessary for the output of #128 to be usable.
