### ISSUE TITLE
Handle case where a stylesheet is configuring an indirect dependency

### ISSUE THREAD

**Issue by jathak** [sass/migrator#28]
Something like this

```scss
// entrypoint.scss
$config: red;
@import "direct";

// _direct.scss
@import "indirect";

// _indirect.scss
$config: green !default;
```

is currently migrated to

```scss
// entrypoint.scss
$config: red;
@use "direct";

// _direct.scss
@use "entrypoint";
@use  "indirect";

// _indirect.scss
$config: green !default;
```

which is definitely wrong, but I'm also not sure what the best way to actually do it would be.

**Comment by nex3** [comment]
I guess something like this:

```scss
// entrypoint.scss
@import "direct" with ($config: red);

// _direct.scss
@forward "indirect";

// _indirect.scss
$config: green !default;
```

**Comment by jathak** [comment]
What about cases like this, where the intermediate dependency also uses the variable that's being configured?

```scss
// entrypoint.scss
$config: red;
@import "direct";

// _direct.scss
@import "indirect";
a {
  b: $config;
}

// _indirect.scss
$config: green !default;
```

This is my best guess, but I'm not sure whether `$indirect.config` would be red or green in this case.

```scss
// entrypoint.scss
$config: red;
@use "direct";

// _direct.scss
@forward "indirect";
@use  "indirect";
a {
  b: $indirect.config;
}

// _indirect.scss
$config: green !default;
```
